# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SwiftKit' do

# Smooth asynchronous user interfaces for iOS apps. : Thanks to Scott Goodson and Facebook team.
pod 'AsyncDisplayKit'

# An embedded syncable NoSQL database for iOS apps.
pod 'couchbase-lite-ios'

# Elegant HTTP Networking in Swift
pod 'Alamofire'

#AlamofireImage is an image component library for Alamofire.
pod 'AlamofireImage'

# An extension to Alamofire which automatically converts JSON response data into swift objects using ObjectMapper.
pod 'AlamofireObjectMapper'

end

target 'SwiftKitTests' do

end

target 'SwiftKitUITests' do

end

