source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftKit_Example', :exclusive => true do
  pod 'SwiftKit', :path => '../'
end

target 'SwiftKit_Tests', :exclusive => true do
  pod 'SwiftKit', :path => '../'

  
end
